#!/usr/bin/bash
# sdk/kernel/lib/configure.sh
# Qualcomm Silicon Workshop — Kernel SDK configuration generation
#
# Implements the verified Ubuntu linux-qcom configuration sequence from
# QUALCOMM_WORKSHOP_DESIGN.md, derived from the stamp-prepare-tree-% target
# in debian/rules.d/2-binary-arch.mk.
#
# Functions:
#   kernel_configure ROOT FLAVOUR KERNELRELEASE RELEASE REVISION JOBS

[[ -n "${_KERNEL_CONFIGURE_SH:-}" ]] && return
_KERNEL_CONFIGURE_SH=1

# kernel_configure ROOT FLAVOUR KERNELRELEASE RELEASE REVISION JOBS
# Generates the kernel .config for the given flavour using the Ubuntu
# annotations machinery.
kernel_configure() {
    local root="${1}"
    local flavour="${2}"
    local kernelrelease="${3}"
    local release="${4}"
    local revision="${5}"
    local jobs="${6:-$(nproc)}"

    local src="${root}/src/kernel/linux-qcom"
    local builddir="${root}/build/kernel/build-${flavour}"

    workshop_log "=== Kernel configuration ==="
    workshop_log "Flavour:      ${flavour}"
    workshop_log "KERNELRELEASE: ${kernelrelease}"
    workshop_log "Build dir:    ${builddir}"

    # Step 1: Create build directory and ubuntu-build marker
    mkdir -p "${builddir}"
    touch "${builddir}/ubuntu-build"

    # Step 2: Export .config from Ubuntu annotations machinery
    # The annotations script must be run from within the kernel source tree
    # (it uses relative paths to locate the DEBIAN/config/annotations file).
    # This is the exact equivalent of:
    #   cd src/kernel/linux-qcom
    #   python3 debian/scripts/misc/annotations \
    #       --export --arch arm64 --flavour ${FLAVOUR} > .config
    workshop_log "Exporting .config from Ubuntu annotations (arch=arm64, flavour=${flavour})..."

    (
        cd "${src}"
        python3 debian/scripts/misc/annotations \
            --export \
            --arch arm64 \
            --flavour "${flavour}"
    ) > "${builddir}/.config" \
        || workshop_fail "annotations --export failed. Check that the source tree is complete."

    [[ -s "${builddir}/.config" ]] || \
        workshop_fail ".config is empty after annotations export."

    workshop_log ".config exported ($(wc -l < "${builddir}/.config") lines)"
    # Step 3a: Create drivers/gpu/drm/msm_default/ directory
    # The linux-qcom SAUCE patches modify drivers/gpu/drm/Makefile to add:
    #   obj-$(CONFIG_DRM_MSM) += msm_default/
    # The msm_default/ directory is a modified copy of drivers/gpu/drm/msm/
    # created by applying debian.qcom/patch/msm_default.diff. It does NOT
    # exist in the git tree and MUST be created before building.
    # (In the Debian packaging path, debian/rules clean creates it. In the
    # direct build path, we must create it ourselves.)
    local msm_default="${src}/drivers/gpu/drm/msm_default"
    if [[ ! -d "${msm_default}" ]]; then
        workshop_log "Creating drivers/gpu/drm/msm_default/ (required SAUCE step)..."
        cp -r "${src}/drivers/gpu/drm/msm" "${msm_default}"
        patch -p1 -d "${src}" < "${src}/debian.${flavour}/patch/msm_default.diff" || \
            workshop_fail "Failed to apply msm_default.diff patch."
        workshop_log "  msm_default/ created and patched."
    else
        workshop_log "  drivers/gpu/drm/msm_default/ already exists."
    fi

    # Step 3b: Generate canonical-certs.pem and canonical-revoked-certs.pem
    # The Ubuntu linux-qcom kernel uses CONFIG_SYSTEM_TRUSTED_KEYS pointing to
    # debian/canonical-certs.pem. This file is generated by debian/rules from
    # the PEM files in debian/certs/. In a direct (non-packaging) build we must
    # generate it before building the kernel image or it becomes a missing target.
    workshop_log "Generating canonical-certs.pem and canonical-revoked-certs.pem..."
    (
        cd "${src}"
        DROOT="debian" DEBIAN="debian.${flavour}" \
            make -f debian/rules \
            debian/canonical-certs.pem \
            debian/canonical-revoked-certs.pem \
            2>&1 | grep -v "^/bin/bash.*gawk" | grep -v "^make\[" || true
    )
    # Verify certs were generated
    [[ -f "${src}/debian/canonical-certs.pem" ]] || \
        workshop_fail "canonical-certs.pem was not generated. Check debian/certs/ directory."
    workshop_log "  canonical-certs.pem: $(wc -c < "${src}/debian/canonical-certs.pem") bytes"
    # Step 3: Set CONFIG_VERSION_SIGNATURE
    # Format matches stamp-prepare-tree-% in 2-binary-arch.mk:
    #   CONFIG_VERSION_SIGNATURE="Ubuntu ${release}-${revision}-${flavour} ${raw_kernelversion}"
    # Where:
    #   release          = abi_release = e.g. "6.8.0-1080"  (release-abinum)
    #   revision         = full revision = e.g. "1080.85"
    #   raw_kernelversion = output of make kernelversion in the source tree
    #                      (for Ubuntu-qcom-6.8.0-1080.85 this is "6.8.12",
    #                       not "6.8.0" — the SUBLEVEL is advanced by SAUCE)
    # Example result: Ubuntu 6.8.0-1080-1080.85-qcom 6.8.12
    # The repeated "1080" is correct: release ends in "-1080", revision starts "1080."
    local upstream_version
    upstream_version="$(make -C "${src}" kernelversion ARCH=arm64 2>/dev/null | head -1)" || {
        # Fallback: extract from Makefile directly
        upstream_version="$(awk '/^VERSION =/{v=$3} /^PATCHLEVEL =/{p=$3} /^SUBLEVEL =/{s=$3} END{print v"."p"."s}' "${src}/Makefile")"
    }
    upstream_version="${upstream_version%%-*}"  # strip any suffix (e.g. -rc)

    # Format from stamp-prepare-tree-% in 2-binary-arch.mk:
    #   CONFIG_VERSION_SIGNATURE="Ubuntu $(release)-$(revision)-$* $(raw_kernelversion)"
    # Where: release = abi_release = e.g. 6.8.0-1080
    #        revision = full revision = e.g. 1080.85
    #        raw_kernelversion = upstream make kernelversion (e.g. 6.8.12 for this tree)
    # Result: Ubuntu 6.8.0-1080-1080.85-qcom 6.8.12
    workshop_log "Setting CONFIG_VERSION_SIGNATURE: Ubuntu ${release}-${revision}-${flavour} ${upstream_version}"
    sed -i \
        "s|.*CONFIG_VERSION_SIGNATURE.*|CONFIG_VERSION_SIGNATURE=\"Ubuntu ${release}-${revision}-${flavour} ${upstream_version}\"|" \
        "${builddir}/.config"

    # Step 4: Resolve config dependencies (olddefconfig)
    # Equivalent to: $(kmake) O=$(builddir) olddefconfig
    workshop_log "Running olddefconfig to resolve configuration dependencies..."
    make -C "${src}" \
        O="${builddir}" \
        ARCH=arm64 \
        CROSS_COMPILE="${CROSS_COMPILE}" \
        CC="${CC}" \
        HOSTCC="${HOSTCC}" \
        olddefconfig \
        2>&1 | sed 's/^/[olddefconfig] /' \
        || workshop_fail "olddefconfig failed."

    workshop_log "Kernel configuration complete: ${builddir}/.config"
}
